#!/bin/bash

prog=medis-server
bin=/usr/local/sbin/
conf=/etc/conf/medis.conf

function get_pid(){
    local pid=0
    ret=$(ps aux |grep ${prog} |grep ${conf} |grep -v grep|awk '{print $2}')
    if [ "x$ret" != "x" ]; then
        echo $ret
        return 0
    fi
    echo 0
}


function service_start(){
    local pid=$(get_pid)
    if [ $pid -ne 0 ]; then
        echo "${prog} is already running"
        RETVAL=1
        return 1
    fi

    ps aux |grep ${prog} |grep -v grep | awk '{print "kill -9 " $2}' | sh
    ${bin}${prog} ${conf}
    sleep 0.1
    local pid=$(get_pid)
    if [ $pid -ne 0 ]; then
        echo "${prog} is start success"
        RETVAL=0
        return 0
    else
        echo "${prog} start error"
        RETVAL=1
        return 1
    fi
}

function service_stop(){
    local pid=$(get_pid)
    if [ $pid -ne 0 ]; then
        kill -15 $pid
        sleep 0.5
    fi
    pid=$(get_pid)
    if [ $pid -ne 0 ]; then
        echo "stop ${prog} error"
        RETVAL=1
        return 1
    else
        echo "stop ${prog} ok"
        RETVAL=0
        return 0
    fi
}


function service_status(){
    local pid=$(get_pid)
    if [ $pid -ne 0 ]; then
        echo "Running"
        RETVAL=0
    else
        echo "Stopped"
        RETVAL=1
    fi
    return 0
}

case "$1" in
start)
    service_start
    ;;
stop)
    service_stop
    ;;
status)
    service_status
    ;;
restart)
    service_stop
    service_start
    ;;
*)
    echo "Usage: medis {start|stop|restart|status}"
    RETVAL=1
esac

exit $RETVAL